name: Build Android APK

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: "4.3.7"

      - name: Setup Android
        uses: android-actions/setup-android@v3

      - name: Install Android SDK
        run: |
          yes | sdkmanager --licenses || true

          sdkmanager "platform-tools"
          sdkmanager "platforms;android-29"
          sdkmanager "platforms;android-35"
          sdkmanager "build-tools;35.0.0"
          sdkmanager "ndk;29.0.13113456"

      - name: Android environment
        run: |
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH

      - name: Setup Haxelib
        run: |
          haxelib setup ~/haxelib

      - name: Install HMM
        run: |
          haxelib install hmm

      - name: Install project dependencies
        run: |
          haxelib run hmm install

      - name: Show Haxelib
        run: |
          haxelib list

      - name: Remove Git Lime
        run: |
          haxelib remove lime || true

      - name: Install Lime release
        run: |
          haxelib install lime

      - name: Check Lime
        run: |
          haxelib list lime
          haxelib libpath lime

      - name: Rebuild Lime native tools
        run: |
          haxelib run lime rebuild cpp

      - name: Setup Lime Android
        run: |
          haxelib run lime setup android

      - name: Build Android APK
        run: |
          haxelib run lime build android -release -DEXCLUDE_ARMV7

      - name: Find APK
        run: |
          find . -type f -name "*.apk" -print

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Funkin-Sun-Android
          path: |
            **/*.apk
          if-no-files-found: error
